export const SET_INGREDIENTS = 'SET_INGREDIENTS';
export const INIT_INGREDIENTS_SAGA = 'INIT_INGREDIENTS_SAGA';
export const ADD_INGREDIENT = 'ADD_INGREDIENT';
export const REMOVE_INGREDIENT = 'REMOVE_INGREDIENT';
export const FETCH_INGREDIENTS_ERROR = 'FETCH_INGREDIENTS_ERROR';

export const PURCHASE_INIT = 'PURCHASE_INIT';
export const PURCHASE_BURGER_SAGA = 'PURCHASE_BURGER_SAGA';
export const PURCHASE_BURGER_START = 'PURCHASE_BURGER_START';
export const PURCHASE_BURGER_SUCCESS = 'PURCHASE_BURGER_SUCCESS';
export const PURCHASE_BURGER_ERROR = 'PURCHASE_BURGER_ERROR';

export const FETCH_ORDERS_SAGA = 'FETCH_ORDERS_SAGA';
export const FETCH_ORDERS_START = 'FETCH_ORDERS_START';
export const FETCH_ORDERS_SUCCESS = 'FETCH_ORDERS_SUCCESS';
export const FETCH_ORDERS_ERROR = 'FETCH_ORDERS_ERROR';

export const AUTH_CHECK_SAGA = 'AUTH_CHECK_INITIAL_SAGA';
export const AUTH_SAGA = 'AUTH_SAGA';
export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_CHECK_TIMEOUT = 'AUTH_CHECK_TIMEOUT';
export const AUTH_ERROR = 'AUTH_ERROR';
export const AUTH_INITIATE_LOGOUT = 'AUTH_INITIATE_LOGOUT';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';
